### Model Accuracy on the training Data:
    73.1%
### Model Accuracy on the [new data] test Data:
    64.3%

In [66]:
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import plot_tree, export_text
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [67]:
customer = pd.read_csv('../datasets/dm_train_t.csv')
test = pd.read_csv('../datasets/dmtest.csv')

In [68]:
customer.head()

id     n24_t   rev24_t  elpsdm_t_t_1  revlast_t_t_1  ordfreq  ordcat  \
0   1  0.693147  3.401197           0.0       4.472136        1       6   
1   2  3.218876  5.332719           0.0       4.472136        1       6   
2   3  1.609438  3.951244           0.0       3.872983        1       6   
3   4  2.397895  4.653960           0.0       3.872983        1       6   
4   5  0.693147  3.465736           0.0       4.123106        1       6   

   response  
0         1  
1         0  
2         0  
3         0  
4         0

In [69]:
customer.shape

(2000, 8)

In [70]:
test.head()

id  n24_t  rev24_t  elpsdm_t_t_1  revlast_t_t_1  ordfreq  ordcat
0  5001      5    186.0            24             18        1       6
1  5002      2     30.0            24             15        1       6
2  5003     24    362.0            24             30        1       7
3  5004      4     41.0            24             15        1       6
4  5005      5     59.0            24             18        1       6

In [71]:
test.shape

(2000, 7)

In [72]:
test.columns

Index(['id', 'n24_t', 'rev24_t', 'elpsdm_t_t_1', 'revlast_t_t_1', 'ordfreq',
       'ordcat'],
      dtype='object')

In [73]:
test_cols = ['n24_t', 'rev24_t', 'elpsdm_t_t_1', 'revlast_t_t_1', 'ordfreq', 'ordcat']

y_test = test[test_cols]

In [74]:
customer.shape

(2000, 8)

In [75]:
customer.dtypes

id                 int64
n24_t            float64
rev24_t          float64
elpsdm_t_t_1     float64
revlast_t_t_1    float64
ordfreq            int64
ordcat             int64
response           int64
dtype: object

In [76]:
customer.columns

Index(['id', 'n24_t', 'rev24_t', 'elpsdm_t_t_1', 'revlast_t_t_1', 'ordfreq',
       'ordcat', 'response'],
      dtype='object')

In [77]:
cols = ['n24_t', 'rev24_t', 'elpsdm_t_t_1', 'revlast_t_t_1', 'ordfreq','ordcat']

x = customer[cols]
y = customer['response']

In [78]:
x_, y_ =train_test_split(y_test, test_size=0.5, random_state=4)

In [79]:
x_.shape

(1000, 6)

In [80]:
rfc_model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=3)

In [81]:
rfc_model.fit(x, y)

RandomForestClassifier(max_depth=5, random_state=3)

In [82]:
rfc_model.score(x, y)

0.7315

In [83]:
rfc_proba = rfc_model.predict_proba(x)
rfc_proba

array([[0.72838781, 0.27161219],
       [0.78095816, 0.21904184],
       [0.79548002, 0.20451998],
       ...,
       [0.78212295, 0.21787705],
       [0.79319062, 0.20680938],
       [0.71090044, 0.28909956]])

In [84]:
rfc_model.estimators_[0]

DecisionTreeClassifier(max_depth=5, max_features='auto', random_state=218175338)

In [85]:
len(rfc_model.estimators_)

100

In [86]:
rfc_model.score(x, y)

0.7315

In [87]:
preds = rfc_model.predict(x_)

In [88]:
fin_accuracy = rfc_model.score(y_, preds)
fin_accuracy

0.643

In [89]:
rfc_proba = rfc_model.predict_proba(y_)
rfc_proba

array([[0.45214399, 0.54785601],
       [0.3712215 , 0.6287785 ],
       [0.44214399, 0.55785601],
       ...,
       [0.57730625, 0.42269375],
       [0.44898321, 0.55101679],
       [0.35625689, 0.64374311]])

In [90]:
rfc_model.classes_

array([0, 1], dtype=int64)

In [91]:
pd.value_counts(preds)

1    744
0    256
dtype: int64